### ISSUE TITLE
[uuf-client] Add a loading animation to the zone until the fragment is rendered

### ISSUE THREAD

**Issue by Shan1024** [wso2/carbon-uuf-common#22]
If the network connection is slow, until the fragment is loaded, there is no indication of something is happening. So we need to add a loading animation to the zone until the the fragment is rendered.

**Comment by this** [comment]
UUF Client cannot provide a loading animation as it doesn't know about the UX requirements of the web app. What UUF Client can provide is a callback. UUF Client can get two callbacks `onSuccess`, `onFail` (similar to jQuery AJAX) as parameters and invoke those callbacks.
