### ISSUE TITLE
Please add jQuery Validation JS lib into uuf-common.

### ISSUE THREAD

**Issue by cnapagoda** [wso2/carbon-uuf-common#27]
@thusithak @this Please looking into this.

**Comment by this** [comment]
@thusithak use approved [jQuery Validation](https://jqueryvalidation.org/) version 1.14.0

**Comment by cnapagoda** [comment]
@thusithak  it will be great if you can add a sample scenario for this.

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-common/pull/64).
