### ISSUE TITLE
Add highlight fragment to the foundation component

### ISSUE THREAD

**Issue by Shan1024** [wso2/carbon-uuf-common#28]
Currently we use highlight fragment in the `features-app` to highlight the code samples. It is currently at the `org.wso2.carbon.uuf.sample.foundation.ui`. We need to add it to the `org.wso2.carbon.uuf.common.foundation.ui` so that we can use that fragment in the sample app in the UUF core.

**Comment by Shan1024** [comment]
@thusithak Can you look into this?

**Comment by thusithak** [comment]
Added with https://github.com/wso2/carbon-uuf-common/pull/40

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-common/pull/64).
