### ISSUE TITLE
Enable i18n support in javascript

### ISSUE THREAD

**Issue by ayshsandu** [wso2/carbon-uuf-common#36]
Can we get a common method to support i18n in serverside javascript level
One common use case is that we need to localize js generated messages such as errors.
   (e.g. sending an error 'sendError' with a message).

**Comment by this** [comment]
This issue belongs in the _wso2/carbon-uuf_ repo. Hence, closed here and migrated to https://github.com/wso2/carbon-uuf/issues/160.
