### ISSUE TITLE
Unable to debug script files within fragments which rendered through UUFClient

### ISSUE THREAD

**Issue by udarakr** [wso2/carbon-uuf-common#55]
These scripts are not listed within the developer tool.
Workaround is to put a manual debug point in the file itself (debugger;) and continue.

**Comment by manuranga** [comment]
Chrome only shows it in debugger correctly if we add using appendChild.

```js
 var script = document.createElement("script");
 script.setAttribute("src", src);
 $('head')[0].appendChild(script);
```

To fix this we need a change from UUF core as well, to store the placeholder values as src array not as a string.

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-common/pull/64).
