### ISSUE TITLE
wso2 logo fragment

### ISSUE THREAD

**Issue by udarakr** [wso2/carbon-uuf-common#9]
Previously we had wso2 logo inside wso2-theme. With the UUF approach if we keep images inside a common fragment no one can't reuse those images. Instead have to duplicate the same image and use,
`<img src="{{public "images/logo-inverse.svg"}}" alt="WSO2" title="WSO2" class="logo">`

So let's create a fragment which render the wso2-logo so other component also can include this fragment.

**Comment by this** [comment]
@thusithak Please create the 'wso2-logo' fragment in the 'foundation' component

**Comment by thusithak** [comment]
Added in https://github.com/wso2/carbon-uuf-common/pull/10

**Comment by this** [comment]
fixed in PR #10
